name: Build and Push API Image

on:
  push:
    paths:
      - 'devops-qr-code/api/**'  # Trigger if any file in the api/ directory changes
      
  workflow_dispatch:  # Allows manual triggering of the workflow
#  workflow_run:
#    workflows: ["Terraform Deployment"]
#    types:
#      - completed

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v2
        with:
          context: ./devops-qr-code/FastAPI/
          file: ./devops-qr-code/FastAPI/dockerfile.api
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/api:latest
