name: 02. Build and Push API Image

on:
  push:
    paths:
      - 'QR_code_app/api/**'  # Trigger the workflow if any file in the API directory changes

  workflow_dispatch:  # Allows manual triggering of the workflow
  # workflow_run:
    # workflows: ["Terraform Deployment"]
    # types:
      # - completed

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest

    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}           # Azure Container Registry name
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}   # Azure Container Registry username
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}   # Azure Container Registry password

    steps:
      - name: Check out the code
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for accurate context and potential debugging

      - name: Set up Docker Buildx
        id: docker
        uses: docker/setup-buildx-action@v2
        # Optionally configure buildx options if necessary
        # with:
        #   drivers: [docker]

      - name: Log in to Azure
        id: log-in
        uses: azure/login@v2  # Authenticate with Azure using a service principal
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # JSON credentials for Azure authentication

      - name: Azure CLI script
        id: cli
        uses: azure/cli@v2  # Set up Azure CLI
        with:
          azcliversion: latest  # Use the latest version of Azure CLI
          inlineScript: |
            az account show  # Display information about the current Azure subscription

      - name: Log in to Azure Container Registry
        id: acr
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io  # URL of the Azure Container Registry
          username: ${{ env.ACR_USERNAME }}         # Username for Azure Container Registry
          password: ${{ env.ACR_PASSWORD }}         # Password for Azure Container Registry

      - name: Build and push API Docker image
        id: push
        uses: docker/build-push-action@v2
        with:
          context: './QR_code_app/api/'  # Directory containing Dockerfile and application files
          file: './QR_code_app/api/dockerfile'  # Path to the Dockerfile
          push: true  # Push the built image to the Azure Container Registry
          tags: ${{ env.ACR_NAME }}.azurecr.io/fastapi:latest  # Tag for the Docker image

      - name: Verify Docker Image
        id: verify
        run: |
          docker pull ${{ env.ACR_NAME }}.azurecr.io/fastapi:latest  # Pull the latest image to verify it exists
          docker images | grep fastapi  # List Docker images to confirm the build
