name: 04. Terraform Destroy

on:
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    defaults:
      run:
        shell: bash  # Set the default shell to bash
        working-directory: './Terraform'  # Set default working directory for all steps

    env:
      # Azure credentials for Terraform
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}           # Azure service principal client ID
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}   # Azure service principal client secret
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}  # Azure subscription ID
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}           # Azure tenant ID

      # Terraform variables for Azure credentials
      TF_VAR_client_id: ${{ secrets.CLIENT_ID }}         # Client ID for Azure resources
      TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}  # Client secret for Azure resources
      TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}  # Subscription ID for Azure resources
      TF_VAR_tenant_id: ${{ secrets.TENANT_ID }}         # Tenant ID for Azure resources

      # Terraform variables for resource configuration
      TF_VAR_resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME }}  # Resource group name for Terraform state
      TF_VAR_storage_account_name: ${{ secrets.STORAGE_ACCOUNT_NAME }}  # Storage account name for Terraform state
      TF_VAR_container_name: ${{ secrets.CONTAINER_NAME }}  # Container name in the storage account for Terraform state
      TF_VAR_key: ${{ secrets.KEY }}  # Key for the Terraform state file

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Check out the repository code to the GitHub Actions runner

      - name: Log in to Azure
        uses: azure/login@v1  # Authenticate with Azure using a service principal
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # JSON credentials for Azure authentication

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1  # Set up the Terraform CLI

      - name: Terraform Init
        id: init
        run: |
          terraform init -migrate-state \
            -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.KEY }}"  # Initialize Terraform and configure the backend state

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve  # Destroy the infrastructure without interactive approval