name: Build and Push API Image

on:
  push:
    paths:
      - 'devops-qr-code/api/**'  # Trigger if any file in the api/ directory changes
      - 'dockerfiles/dockerfile.api'  # Trigger if the dockerfile changes
      
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: acralextestproject.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/
          file: ./dockerfiles/dockerfile.api
          push: true
          tags: acralextestproject.azurecr.io/api:latest
