name: Build and Push Frontend Image

on:
  push:
    paths:
      - 'devops-qr-code/front-end-nextjs/**'  # Trigger if any file in the frontend/ directory changes
    
  workflow_dispatch:  # Allows manual triggering of the workflow
  workflow_run:
    workflows: ["Terraform Deployment"]
    types:
      - completed
jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: acralextestproject.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./devops-qr-code/Node.js/
          file: ./devops-qr-code/Node.js/dockerfile.fen
          push: true
          tags: acralextestproject.azurecr.io/front-end-nextjs:latest
