name: Build and Push Frontend Image

on:
  push:
    paths:
      - 'devops-qr-code/front-end-nextjs/**'  # Trigger if any file in the frontend/ directory changes
    
  workflow_dispatch:  # Allows manual triggering of the workflow
  workflow_run:
    workflows: ["Terraform Deployment"]
    types:
      - completed
 
jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets[env.ACR_NAME] }}.azurecr.io
          username: ${{ secrets[env.ACR_USERNAME] }}
          password: ${{ secrets[env.ACR_PASSWORD] }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./devops-qr-code/Node.js/
          file: ./devops-qr-code/Node.js/dockerfile.fen
          push: true
          tags: ${{ secrets[env.ACR_NAME] }}.azurecr.io/front-end-nextjs:latest
