name: Terraform Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:  # Allows manual triggering of the workflow

env:
  TF_VAR_api_key: ${{ secrets.API_KEY }}
  TF_VAR_private_key: ${{ secrets.PRIVATE_KEY }}
  TF_VAR_url: ${{ secrets.url }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: |
         tf_actions_version: 0.12.13
         tf_actions_subcommand: "init"
         args: -var=storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}"
               -var="container_name=${{ secrets.CONTAINER_NAME }}"
               -var="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" 
               -var="key=${{ secrets.BACKEND_KEY }}" 
               -var="access_key=${{ secrets.ACCESS_KEY }}"
    
      - name: "Terraform Plan"    
        uses: hashicorp/terraform-github-actions@master
        with:
         tf_actions_version: 0.12.13
         tf_actions_subcommand: "plan"
         args: -var="client_secret=${{ secrets.clientSecret }}"
               -var="client_id=${{ secrets.clientId }}"
               -var="tenant_id=${{ secrets.tenantId }}"
               -var="sub=${{ secrets.sub }}"

      - name: Terraform Apply
        run: terraform apply main.tfplan -auto-approve
